AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Cloud Formation Template to allow for selection of various sizes of EC2
  instances
Parameters: 
  Environment:
    Description: Which account is the environment being creates
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  SubnetId:
    Description: my testing subnetID
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0cc5c399dbddd3d5e
  myVPC:
    Description: My testing vpc
    Type: AWS::EC2::VPC::Id
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  AvailabilityZone1:
    Description: The first availability zone in the region
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1
    ConstraintDescription: Must be a valid availability zone

Mappings: 
  EC2Details:
    CommonDetails:
      #VPC: 
      Name: 'filler testing name'
      #!Join ['-', [!Ref AWS::Region, Instance, 'jacob']]


    dev:
      AvailabilityZone: us-east-1
      #InstanceType:
      KeyName: JacobDevKey
      KeyId: ea3666be-9460-47a6-84c2-58638bdbae52
      #SubnetId:
      #SecurityGroupIds:
      
    prod:
      AvailabilityZone: us-east-1
      #InstanceType:
      KeyName: JacobProdKey
      KeyId: cfea61f1-38e9-4e43-9557-aa562a701aba
      #SubnetId:
      #SecurityGroupIds:
    qa:
      AvailabilityZone: us-east-1
      #InstanceType:
      KeyName: JacobQaKey
      KeyId: b76c6a3f-535f-40d5-b3af-3f07ac8a3b09
      #SubnetId:
      #SecurityGroupIds:


  RegionAndInstanceTypeToAMIID: 
      us-east-1: 
        dev: 'ami-0022c769'
        prod: 'ami-0022c769'
Conditions:
  Prod: 
    !Equals
        - !Ref Environment  
        - prod 
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      #change these to !FindInMap
      KeyName: !FindInMap ['EC2Details', !Ref Environment, !Ref KeyName]
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
      - !Ref 'InstanceSecurityGroup'
      InstanceType: m1.small
      AvailabilityZone: !Ref AvailabilityZone1
      ImageId: !FindInMap [RegionAndInstanceTypeToAMIID, !Ref "AWS::Region", !Ref Environment]
      #is in
      UserData: 
        Fn::Base64:
          !Sub |
            #!/bin/bash -ex
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
            sudo yum install -y yum-utils
            sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
            sudo yum -y install vault
      Tags:
        -
          Key: Name
          Value: !FindInMap ['EC2Details', 'CommonDetails', 'Name']
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to client host
        VpcId: !Ref myVPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 443
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 443
          CidrIp: 0.0.0.0/0
        Tags:
        -
          Key: Name
          Value: !Join ['-', [SecurityGroup, !Ref AWS::Region, !Ref Environment]]

